/// A Data Transfer Object (DTO) that holds the results of an encryption operation,
/// including the encrypted payload, the initialization vector (nonce), and the
/// authentication tag.
class CryptoDto {
  /// The encrypted message payload, encoded as a Base64 string.
  String payLoad;

  /// The initialization vector used for encryption, encoded as a Base64 string.
  /// This must be unique for every encryption operation with the same key.
  String nonce;

  /// The authentication tag generated by the GCM cipher, encoded as a Base64 string.
  /// This is used to verify the integrity and authenticity of the message.
  String tag;

  /// Creates a [CryptoDto] with the given [payLoad], [nonce], and [tag].
  CryptoDto({required this.payLoad, required this.nonce, required this.tag});
}
